/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ReferenceAudio: typeof import('./components/ReferenceAudio.vue')['default']
    UserRecording: typeof import('./components/UserRecording.vue')['default']
    WaveformPlayer: typeof import('./components/WaveformPlayer.vue')['default']
  }
}
